### ISSUE TITLE
Reference document for EXPRESS syntax

### ISSUE THREAD

**Issue by tymokvo** [expresslang/syntax#2]
Hello,

I found this repository while looking for references on the EXPRESS syntax. Is the only way to get an authoritative source on this to purchase the [ISO document](https://www.iso.org/standard/38047.html)?

My use case is for developing SDK generation for IFC files. So, naturally, a PDF is not very helpful in this regard.

Thanks for any help!

**Comment by TRThurman** [comment]
Here is a development site for one of the EXPRESS language tools.
https://sourceforge.net/projects/exp-engine/
The bnfs for part 11 and part 21 are included as well as a developer manual that may be of interest.

You should also check out the IFC site.
And stepcode site.

**Comment by tymokvo** [comment]
Awesome, thank you!

**Comment by ronaldtse** [comment]
@tymokvo you can also find the ANTLR grammar for EXPRESS here:

- https://github.com/lutaml/express-grammar/tree/master

Hope this helps!
